// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QLMuaHangVaNCC_UNETI06_TI17A1HN.Migrations
{
    [DbContext(typeof(QLMuaHangVaNCC_UNETI06_TI17A1HNContext))]
    [Migration("20261001005819_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.BoPhanDeNghi", b =>
                {
                    b.Property<int>("MaBoPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBoPhan"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NguoiPhuTrach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenBoPhan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaBoPhan");

                    b.ToTable("BoPhanDeNghi");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ChiTietDonMua", b =>
                {
                    b.Property<int>("MaChiTietDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDon"));

                    b.Property<decimal>("DonGiaMua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaChiTietYeuCau")
                        .HasColumnType("int");

                    b.Property<int>("MaDonMua")
                        .HasColumnType("int");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDat")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietDon");

                    b.HasIndex("MaChiTietYeuCau");

                    b.HasIndex("MaDonMua");

                    b.HasIndex("MaHang");

                    b.ToTable("ChiTietDonMua");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ChiTietGiaoHang", b =>
                {
                    b.Property<int>("MaChiTietGiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietGiao"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaChiTietDon")
                        .HasColumnType("int");

                    b.Property<int>("MaLanGiao")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongDatChatLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhan")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietGiao");

                    b.HasIndex("MaChiTietDon");

                    b.HasIndex("MaLanGiao");

                    b.ToTable("ChiTietGiaoHang");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ChiTietYeuCau", b =>
                {
                    b.Property<int>("MaChiTietYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietYeuCau"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<int>("MaYeuCau")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDuyet")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongYeuCau")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietYeuCau");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaYeuCau");

                    b.ToTable("ChiTietYeuCau");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.DonMuaHang", b =>
                {
                    b.Property<int>("MaDonMua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonMua"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("MaYeuCau")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiLap")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDonMua");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaYeuCau");

                    b.HasIndex("NguoiLap");

                    b.ToTable("DonMuaHang");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.DonViTinh", b =>
                {
                    b.Property<int>("MaDonViTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonViTinh"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenDonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDonViTinh");

                    b.ToTable("DonViTinh");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.HangHoa", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"));

                    b.Property<decimal>("GiaThamKhao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDonViTinh")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiHang")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaHang");

                    b.HasIndex("MaDonViTinh");

                    b.HasIndex("MaLoaiHang");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.LanGiaoHang", b =>
                {
                    b.Property<int>("MaLanGiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLanGiao"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDonMua")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiNhan")
                        .HasColumnType("int");

                    b.Property<string>("SoChungTu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLanGiao");

                    b.HasIndex("MaDonMua");

                    b.HasIndex("NguoiNhan");

                    b.ToTable("LanGiaoHang");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.LichSuTrangThai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiDoiTuong")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaDoiTuong")
                        .HasColumnType("int");

                    b.Property<int>("NguoiThucHien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiCu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TrangThaiMoi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiThucHien");

                    b.ToTable("LichSuTrangThai");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.LoaiHang", b =>
                {
                    b.Property<int>("MaLoaiHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiHang"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoaiHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiHang");

                    b.ToTable("LoaiHang");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NguoiLienHe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNhaCungCap");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.NhaCungCapHangHoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGiaBao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatGia")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ThoiGianGiaoDuKien")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("NhaCungCapHangHoa");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ThanhToanDonMua", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDonMua")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiThucHien")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("SoTienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDonMua");

                    b.HasIndex("NguoiThucHien");

                    b.ToTable("ThanhToanDonMua");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.YeuCauMuaHang", b =>
                {
                    b.Property<int>("MaYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuCau"));

                    b.Property<string>("LyDoMua")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LyDoTuChoiHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaBoPhan")
                        .HasColumnType("int");

                    b.Property<string>("MucDoUuTien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayCanHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayYeuCau")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyet")
                        .HasColumnType("int");

                    b.Property<int>("NguoiLap")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaYeuCau");

                    b.HasIndex("MaBoPhan");

                    b.HasIndex("NguoiDuyet");

                    b.HasIndex("NguoiLap");

                    b.ToTable("YeuCauMuaHang");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ChiTietDonMua", b =>
                {
                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ChiTietYeuCau", "ChiTietYeuCau")
                        .WithMany("ChiTietDonMuas")
                        .HasForeignKey("MaChiTietYeuCau")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.DonMuaHang", "DonMuaHang")
                        .WithMany("ChiTietDonMuas")
                        .HasForeignKey("MaDonMua")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.HangHoa", "HangHoa")
                        .WithMany("ChiTietDonMuas")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChiTietYeuCau");

                    b.Navigation("DonMuaHang");

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ChiTietGiaoHang", b =>
                {
                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ChiTietDonMua", "ChiTietDonMua")
                        .WithMany("ChiTietGiaoHangs")
                        .HasForeignKey("MaChiTietDon")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.LanGiaoHang", "LanGiaoHang")
                        .WithMany("ChiTietGiaoHangs")
                        .HasForeignKey("MaLanGiao")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChiTietDonMua");

                    b.Navigation("LanGiaoHang");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ChiTietYeuCau", b =>
                {
                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.HangHoa", "HangHoa")
                        .WithMany("ChiTietYeuCaus")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.YeuCauMuaHang", "YeuCauMuaHang")
                        .WithMany("ChiTietYeuCaus")
                        .HasForeignKey("MaYeuCau")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("YeuCauMuaHang");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.DonMuaHang", b =>
                {
                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("DonMuaHangs")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.YeuCauMuaHang", "YeuCauMuaHang")
                        .WithMany("DonMuaHangs")
                        .HasForeignKey("MaYeuCau")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.TaiKhoan", "NguoiLapNavigation")
                        .WithMany("DonMuaHangs")
                        .HasForeignKey("NguoiLap")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiLapNavigation");

                    b.Navigation("NhaCungCap");

                    b.Navigation("YeuCauMuaHang");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.HangHoa", b =>
                {
                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.DonViTinh", "DonViTinh")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaDonViTinh")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.LoaiHang", "LoaiHang")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaLoaiHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiHang");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.LanGiaoHang", b =>
                {
                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.DonMuaHang", "DonMuaHang")
                        .WithMany("LanGiaoHangs")
                        .HasForeignKey("MaDonMua")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.TaiKhoan", "NguoiNhanNavigation")
                        .WithMany("LanGiaoHangs")
                        .HasForeignKey("NguoiNhan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DonMuaHang");

                    b.Navigation("NguoiNhanNavigation");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.LichSuTrangThai", b =>
                {
                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.TaiKhoan", "NguoiThucHienNavigation")
                        .WithMany("LichSuTrangThais")
                        .HasForeignKey("NguoiThucHien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiThucHienNavigation");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.NhaCungCapHangHoa", b =>
                {
                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.HangHoa", "HangHoa")
                        .WithMany("NhaCungCapHangHoas")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("NhaCungCapHangHoas")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ThanhToanDonMua", b =>
                {
                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.DonMuaHang", "DonMuaHang")
                        .WithMany("ThanhToanDonMuas")
                        .HasForeignKey("MaDonMua")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.TaiKhoan", "NguoiThucHienNavigation")
                        .WithMany("ThanhToanDonMuas")
                        .HasForeignKey("NguoiThucHien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DonMuaHang");

                    b.Navigation("NguoiThucHienNavigation");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.YeuCauMuaHang", b =>
                {
                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.BoPhanDeNghi", "BoPhanDeNghi")
                        .WithMany("YeuCauMuaHangs")
                        .HasForeignKey("MaBoPhan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.TaiKhoan", "NguoiDuyetNavigation")
                        .WithMany("YeuCauMuaHangsNguoiDuyet")
                        .HasForeignKey("NguoiDuyet")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.TaiKhoan", "NguoiLapNavigation")
                        .WithMany("YeuCauMuaHangsNguoiLap")
                        .HasForeignKey("NguoiLap")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BoPhanDeNghi");

                    b.Navigation("NguoiDuyetNavigation");

                    b.Navigation("NguoiLapNavigation");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.BoPhanDeNghi", b =>
                {
                    b.Navigation("YeuCauMuaHangs");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ChiTietDonMua", b =>
                {
                    b.Navigation("ChiTietGiaoHangs");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.ChiTietYeuCau", b =>
                {
                    b.Navigation("ChiTietDonMuas");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.DonMuaHang", b =>
                {
                    b.Navigation("ChiTietDonMuas");

                    b.Navigation("LanGiaoHangs");

                    b.Navigation("ThanhToanDonMuas");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.DonViTinh", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.HangHoa", b =>
                {
                    b.Navigation("ChiTietDonMuas");

                    b.Navigation("ChiTietYeuCaus");

                    b.Navigation("NhaCungCapHangHoas");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.LanGiaoHang", b =>
                {
                    b.Navigation("ChiTietGiaoHangs");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.LoaiHang", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.NhaCungCap", b =>
                {
                    b.Navigation("DonMuaHangs");

                    b.Navigation("NhaCungCapHangHoas");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.TaiKhoan", b =>
                {
                    b.Navigation("DonMuaHangs");

                    b.Navigation("LanGiaoHangs");

                    b.Navigation("LichSuTrangThais");

                    b.Navigation("ThanhToanDonMuas");

                    b.Navigation("YeuCauMuaHangsNguoiDuyet");

                    b.Navigation("YeuCauMuaHangsNguoiLap");
                });

            modelBuilder.Entity("QLMuaHangVaNCC_UNETI06_TI17A1HN.Models.YeuCauMuaHang", b =>
                {
                    b.Navigation("ChiTietYeuCaus");

                    b.Navigation("DonMuaHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
